# Generated by Django 5.1.5 on 2025-02-05 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MissingCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('photo', models.ImageField(upload_to='missing_photos/')),
                ('missing_date', models.DateField()),
                ('last_seen_location', models.TextField()),
                ('special_features', models.TextField(blank=True, null=True)),
                ('parent_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('parent_phone_number', models.CharField(max_length=15)),
            ],
        ),
    ]
